# .streamlit/secrets.toml

[connections_snowflake]
account='vj89581.eu-central-2.aws'
user='gals'
password='Galshuler1910ifat!'
database='TESTS'
schema='PUBLIC'
role = 'ACCOUNTADMIN'
warehouse = 'COMPUTE_WH'
client_session_keep_alive = true


[connections.snowflake]
account='vj89581.eu-central-2.aws'
user='gals'
password='Galshuler1910ifat!'
database='TESTS'
schema='PUBLIC'
role = 'ACCOUNTADMIN'
warehouse = 'COMPUTE_WH'
client_session_keep_alive = true